#!/bin/bash

DIR="/srv/sysAPI"

echo "Starting webserver..."
cd $DIR
env/bin/python $DIR/app/__init__.py > $DIR/server.log 2>&1 &
PID=$!
echo "Webserver started with PID $PID"
echo $PID > /var/run/sysAPI.pid

exit 0